"""empty message

Revision ID: 3d2bcecb9168
Revises: d3ae5f5e690b
Create Date: 2017-05-19 22:20:58.128715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2bcecb9168'
down_revision = 'd3ae5f5e690b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_registered_on'), 'users', ['registered_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_registered_on'), table_name='users')
    # ### end Alembic commands ###
