"""empty message

Revision ID: d3ae5f5e690b
Revises: da9da5753be1
Create Date: 2017-05-19 21:00:23.356928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3ae5f5e690b'
down_revision = 'da9da5753be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('registered_on', sa.TIMESTAMP(timezone=True), nullable=False))
    op.alter_column('users', 'confirmed_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'confirmed_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('users', 'registered_on')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
