"""empty message

Revision ID: da9da5753be1
Revises: b7f5b5539aee
Create Date: 2017-05-19 12:00:51.205621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9da5753be1'
down_revision = 'b7f5b5539aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_active'), 'users', ['active'], unique=False)
    op.create_index(op.f('ix_users_confirmed_at'), 'users', ['confirmed_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_confirmed_at'), table_name='users')
    op.drop_index(op.f('ix_users_active'), table_name='users')
    # ### end Alembic commands ###
